# Generated by Django 3.0.4 on 2020-04-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=150)),
                ('created_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
    ]
