# Generated by Django 3.0.4 on 2020-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200405_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='pics'),
        ),
    ]
